### ISSUE TITLE
bestgems.org site not updating

### ISSUE THREAD

**Issue by aithscel** [xmisao/bestgems.org#102]
Hi xmisao,

hope you are doing well.

in case you dont already know, it seems that the bestgems site is not updating since a few days.

IT Would be great if you can fix it.

Thanks

**Comment by xmisao** [comment]
Thanks for letting me know.
I'll look into it.

**Comment by xmisao** [comment]
It seems to be an effect of this change in RubyGems.org.

https://github.com/rubygems/rubygems.org/pull/2738

I can probably fix it, so please wait a bit.
