### ISSUE TITLE
Question: Batch is working?

### ISSUE THREAD

**Issue by miyataka** [xmisao/bestgems.org#104]
- web server is running.
- latest date of graph is 2021-07-13. And Today is 2021-07-18 JST.
- For example => https://bestgems.org/gems/bundler

![image](https://user-images.githubusercontent.com/15692588/126041223-dce92feb-b063-4817-9731-91d8c5cbf8db.png)

![image](https://user-images.githubusercontent.com/15692588/126041233-b629d35d-9964-49f8-adb2-39fe7f50225b.png)

P.S.
Thank you for your great service!!

**Comment by patrikjohansson** [comment]
This was fixed in https://github.com/xmisao/bestgems.org/issues/102 and the batch job seem to have updated the stats.

![image](https://user-images.githubusercontent.com/114651/126044568-dfda4f49-a918-48cb-ad74-d08ccfa621a2.png)

**Comment by miyataka** [comment]
@patrikjohansson 
Thanks! I missed it.
