### ISSUE TITLE
[Bug] Popular Versions (Major.Minor) are incorrect

### ISSUE THREAD

**Issue by oliverhamboerger** [xmisao/bestgems.org#78]
For some gems e.g. http://bestgems.org/gems/cvss-suite the statistics for Popular Versions (Major.Minor) is not correct.

I found a few gems where the statistics is wrong but there are also a lot of gems where the statistics is correct.

**Comment by xmisao** [comment]
Hello, @oliverhamboerger 

Thank you for your reporting. This problem had occurred due to the frontend code's bug.

Currently, BestGems.org is displaying popular versions correctly.
