### ISSUE TITLE
Num of Versions is 0 in trends

### ISSUE THREAD

**Issue by khiav223577** [xmisao/bestgems.org#98]
See: https://bestgems.org/gems/multi_range
There are 9 versions actually https://rubygems.org/gems/multi_range/versions

![image](https://user-images.githubusercontent.com/4011729/101313574-5e64a680-3891-11eb-8986-8859ecb63e04.png)

**Comment by xmisao** [comment]
Thanks for your feedback. Probably a bug. I'll look it up next weekend.

**Comment by xmisao** [comment]
@khiav223577 Thanks for waiting. It's fixed.
https://bestgems.org/gems/multi_range
